on: [push]

jobs:
  build:
    runs-on: docker
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: "npm"
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
        env:
          NODE_ENV: production
      - name: Create deployment archive
        run: |
          cd dist
          tar -czf ../taxborn.com-${{ github.run_number }}.tar.gz .
          cd ..
      - name: Upload deployment artifact
        uses: actions/upload-artifact@v3
        with:
          name: taxborn.com-deploy-${{ github.run_number }}
          path: taxborn.com-${{ github.run_number }}.tar.gz
      # TODO: Deploy in a seperate step to avoid recompiling the same artifact if the deployment fails
      #       and the CI needs to be rerun.
      - name: Deploy to server
        if: github.ref == 'refs/heads/main'
        run: |
          # Install SSH key
          mkdir -p ~/.ssh
          echo '${{ secrets.DEPLOY_SSH_KEY }}' > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key

          # Add server to known hosts
          ssh-keyscan -H '${{ secrets.DEPLOY_HOST }}' >> ~/.ssh/known_hosts

          # Upload and deploy the tar file
          scp -i ~/.ssh/deploy_key taxborn.com-${{ github.run_number }}.tar.gz deploy@${{ secrets.DEPLOY_HOST }}:/tmp/
          ssh -i ~/.ssh/deploy_key deploy@${{ secrets.DEPLOY_HOST }} './deploy.sh taxborn.com /tmp/taxborn.com-${{ github.run_number }}.tar.gz'
