# CI for taxborn.com - this just tests that everything compiles and
# tests pass.
#
# Forgejo Workflow reference: https://forgejo.org/docs/latest/user/actions/#workflow-reference-guide

on: [push]

jobs:
  test:
    runs-on: docker
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1 # only get the most recent commit
      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/Jod'
      - run: npm i
      # - run: npm run test # waiting to write actual tests
  build-and-upload:
    runs-on: docker
    needs: test # don't build if test doesn't work
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1 # only get the most recent commit
      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/Jod'
      - run: npm i
      - run: npm run build
      - uses: actions/upload-artifact@v3
        with:
          name: built astro site
          path: dist
  bundle:
    runs-on: docker
    needs: build-and-upload
    steps:
      - run: echo "Working"

