on: [push]

jobs:
  build:
    runs-on: docker
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
      - name: Build
        run: npx astro build
        env:
          NODE_ENV: production
      - name: Deploy
        run: echo "Deploying to carbon..."
      # rsync dist folder to carbon
      - name: Deploy to Carbon
        run: echo "TODO rsync -avz dist/ carbon:/var/www/html/"
