on: [push]

jobs:
  build:
    runs-on: docker
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: "npm"
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
        env:
          NODE_ENV: production
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: taxborn.com-build-${{ github.run_number }}
          path: dist/
      - name: Deploy
        run: echo "Deploying to carbon..."
      # rsync dist folder to carbon
      - name: Deploy to Carbon
        run: echo "TODO rsync -avz dist/ carbon:/var/www/html/"
