on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            # Install npm dependencies
            - name: Install dependencies
              run: npm install
            - name: Build
              run: npm run build
            # Create a artifact from the dist/ folder
            - name: Archive production artifact
              uses: actions/upload-artifact@v4
              with:
                  path: dist 
                  name: dist
    deploy:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Download artifact
              uses: actions/download-artifact@v4
              with:
                  name: dist
                  path: website
            - name: Setup SSH key
              run: |
                mkdir -p ~/.ssh
                echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
                chmod 600 ~/.ssh/id_rsa
                ssh-keyscan -t rsa ${{ secrets.NEON_SSH_HOST }} >> ~/.ssh/known_hosts
            - name: Deploy
              run: scp -r website/* ${{ secrets.NEON_SSH_USER }}@${{ secrets.NEON_SSH_HOST }}:/var/www/www.taxborn.com